-- Complete Seed Data: 40 LeetCode + 10 ML System Design Questions
-- Optimized for Meta & Atlassian Senior ML Engineer Interviews
-- Generated by generate_seed_sql.py
-- 
-- Distribution:
--   LeetCode: 5 Easy, 27 Medium, 8 Hard = 40 Total
--   ML Design: 10 questions
--
-- Meta-specific additions: Sparse Vectors, K Closest Points, Buildings with Ocean View, etc.
-- Atlassian-specific: Search/Discovery system for Jira/Confluence

-- Ensure categories exist
INSERT OR IGNORE INTO question_categories (id, name, description) VALUES
    (1, 'leetcode', 'LeetCode-style coding problems'),
    (2, 'ml_system_design', 'Machine Learning System Design questions');

-- ============================================
-- LEETCODE QUESTIONS
-- ============================================

-- Question 1: Two Sum
-- Two Sum (EASY)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(1, 1, 'Two Sum', 'easy',
'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.',
'["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "-10^9 <= target <= 10^9", "Only one valid answer exists"]',
'[{"input": {"nums": [2, 7, 11, 15], "target": 9}, "output": [0, 1], "explanation": "Because nums[0] + nums[1] == 9, we return [0, 1]."}, {"input": {"nums": [3, 2, 4], "target": 6}, "output": [1, 2], "explanation": "Because nums[1] + nums[2] == 6, we return [1, 2]."}]',
'["array", "hash-table"]',
'["LeetCode URL: https://leetcode.com/problems/two-sum/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(1,
'class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        pass',
'class Solution {
    public int[] twoSum(int[] nums, int target) {
        
    }
}',
'class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        
    }
};',
'[{"input": [[2, 7, 11, 15], 9], "expectedOutput": [0, 1]}, {"input": [[3, 2, 4], 6], "expectedOutput": [1, 2]}, {"input": [[3, 3], 6], "expectedOutput": [0, 1]}]',
'O(n)',
'O(n)');


-- Question 2: Valid Parentheses
-- Valid Parentheses (EASY)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(2, 1, 'Valid Parentheses', 'easy',
'Given a string s containing just the characters ''('', '')'', ''{'', ''}'', ''['' and '']'', determine if the input string is valid.

An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
3. Every close bracket has a corresponding open bracket of the same type.',
'["1 <= s.length <= 10^4", "s consists of parentheses only ''()[]{}''"]',
'[{"input": {"s": "()"}, "output": true, "explanation": "The string is valid."}, {"input": {"s": "()[]{}"}, "output": true, "explanation": "All brackets are properly closed."}, {"input": {"s": "(]"}, "output": false, "explanation": "Mismatched brackets."}]',
'["string", "stack"]',
'["LeetCode URL: https://leetcode.com/problems/valid-parentheses/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(2,
'class Solution:
    def isValid(self, s: str) -> bool:
        pass',
'class Solution {
    public boolean isValid(String s) {
        
    }
}',
'class Solution {
public:
    bool isValid(string s) {
        
    }
};',
'[{"input": ["()"], "expectedOutput": true}, {"input": ["()[]{}"], "expectedOutput": true}, {"input": ["(]"], "expectedOutput": false}, {"input": ["([)]"], "expectedOutput": false}]',
'O(n)',
'O(n)');


-- Question 3: Best Time to Buy and Sell Stock
-- Best Time to Buy and Sell Stock (EASY)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(3, 1, 'Best Time to Buy and Sell Stock', 'easy',
'You are given an array prices where prices[i] is the price of a given stock on the ith day.

You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.

Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.',
'["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"]',
'[{"input": {"prices": [7, 1, 5, 3, 6, 4]}, "output": 5, "explanation": "Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5."}, {"input": {"prices": [7, 6, 4, 3, 1]}, "output": 0, "explanation": "In this case, no transactions are done and the max profit = 0."}]',
'["array", "dynamic-programming"]',
'["LeetCode URL: https://leetcode.com/problems/best-time-to-buy-and-sell-stock/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(3,
'class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        pass',
'class Solution {
    public int maxProfit(int[] prices) {
        
    }
}',
'class Solution {
public:
    int maxProfit(vector<int>& prices) {
        
    }
};',
'[{"input": [[7, 1, 5, 3, 6, 4]], "expectedOutput": 5}, {"input": [[7, 6, 4, 3, 1]], "expectedOutput": 0}]',
'O(n)',
'O(1)');


-- Question 4: Climbing Stairs
-- Climbing Stairs (EASY)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(4, 1, 'Climbing Stairs', 'easy',
'You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?',
'["1 <= n <= 45"]',
'[{"input": {"n": 2}, "output": 2, "explanation": "There are two ways: 1. 1 step + 1 step, 2. 2 steps"}, {"input": {"n": 3}, "output": 3, "explanation": "There are three ways: 1. 1+1+1, 2. 1+2, 3. 2+1"}]',
'["dynamic-programming", "math"]',
'["LeetCode URL: https://leetcode.com/problems/climbing-stairs/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(4,
'class Solution:
    def climbStairs(self, n: int) -> int:
        pass',
'class Solution {
    public int climbStairs(int n) {
        
    }
}',
'class Solution {
public:
    int climbStairs(int n) {
        
    }
};',
'[{"input": [2], "expectedOutput": 2}, {"input": [3], "expectedOutput": 3}, {"input": [4], "expectedOutput": 5}]',
'O(n)',
'O(1)');


-- Question 5: Linked List Cycle
-- Linked List Cycle (EASY)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(5, 1, 'Linked List Cycle', 'easy',
'Given head, the head of a linked list, determine if the linked list has a cycle in it.

There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer.',
'["The number of the nodes in the list is in the range [0, 10^4]", "-10^5 <= Node.val <= 10^5", "pos is -1 or a valid index in the linked-list"]',
'[{"input": {"head": [3, 2, 0, -4], "pos": 1}, "output": true, "explanation": "There is a cycle where the tail connects to the 1st node."}, {"input": {"head": [1], "pos": -1}, "output": false, "explanation": "There is no cycle in the linked list."}]',
'["linked-list", "two-pointers", "hash-table"]',
'["LeetCode URL: https://leetcode.com/problems/linked-list-cycle/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(5,
'class Solution:
    def hasCycle(self, head: Optional[ListNode]) -> bool:
        pass',
'class Solution {
    public boolean hasCycle(ListNode head) {
        
    }
}',
'class Solution {
public:
    bool hasCycle(ListNode *head) {
        
    }
};',
'[{"input": [[3, 2, 0, -4], 1], "expectedOutput": true}, {"input": [[1, 2], 0], "expectedOutput": true}, {"input": [[1], -1], "expectedOutput": false}]',
'O(n)',
'O(1)');


-- Question 6: Longest Substring Without Repeating Characters
-- Longest Substring Without Repeating Characters (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(6, 1, 'Longest Substring Without Repeating Characters', 'medium',
'Given a string s, find the length of the longest substring without repeating characters.',
'["0 <= s.length <= 5 * 10^4", "s consists of English letters, digits, symbols and spaces"]',
'[{"input": {"s": "abcabcbb"}, "output": 3, "explanation": "The answer is ''abc'', with the length of 3."}, {"input": {"s": "bbbbb"}, "output": 1, "explanation": "The answer is ''b'', with the length of 1."}]',
'["string", "sliding-window", "hash-table"]',
'["LeetCode URL: https://leetcode.com/problems/longest-substring-without-repeating-characters/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(6,
'class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        pass',
'class Solution {
    public int lengthOfLongestSubstring(String s) {
        
    }
}',
'class Solution {
public:
    int lengthOfLongestSubstring(string s) {
        
    }
};',
'[{"input": ["abcabcbb"], "expectedOutput": 3}, {"input": ["bbbbb"], "expectedOutput": 1}, {"input": ["pwwkew"], "expectedOutput": 3}]',
'O(n)',
'O(min(m,n))');


-- Question 7: Add Two Numbers
-- Add Two Numbers (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(7, 1, 'Add Two Numbers', 'medium',
'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.

You may assume the two numbers do not contain any leading zero, except the number 0 itself.',
'["The number of nodes in each linked list is in the range [1, 100]", "0 <= Node.val <= 9", "It is guaranteed that the list represents a number that does not have leading zeros"]',
'[{"input": {"l1": [2, 4, 3], "l2": [5, 6, 4]}, "output": [7, 0, 8], "explanation": "342 + 465 = 807."}, {"input": {"l1": [0], "l2": [0]}, "output": [0], "explanation": "0 + 0 = 0."}]',
'["linked-list", "math", "recursion"]',
'["LeetCode URL: https://leetcode.com/problems/add-two-numbers/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(7,
'class Solution:
    def addTwoNumbers(self, l1: Optional[ListNode], l2: Optional[ListNode]) -> Optional[ListNode]:
        pass',
'class Solution {
    public ListNode addTwoNumbers(ListNode l1, ListNode l2) {
        
    }
}',
'class Solution {
public:
    ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {
        
    }
};',
'[{"input": [[2, 4, 3], [5, 6, 4]], "expectedOutput": [7, 0, 8]}, {"input": [[0], [0]], "expectedOutput": [0]}, {"input": [[9, 9, 9], [9, 9, 9, 9]], "expectedOutput": [8, 9, 9, 0, 1]}]',
'O(max(m,n))',
'O(max(m,n))');


-- Question 8: Container With Most Water
-- Container With Most Water (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(8, 1, 'Container With Most Water', 'medium',
'You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]).

Find two lines that together with the x-axis form a container, such that the container contains the most water.

Return the maximum amount of water a container can store.',
'["n == height.length", "2 <= n <= 10^5", "0 <= height[i] <= 10^4"]',
'[{"input": {"height": [1, 8, 6, 2, 5, 4, 8, 3, 7]}, "output": 49, "explanation": "The max area is between index 1 (height 8) and index 8 (height 7)."}]',
'["array", "two-pointers", "greedy"]',
'["LeetCode URL: https://leetcode.com/problems/container-with-most-water/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(8,
'class Solution:
    def maxArea(self, height: List[int]) -> int:
        pass',
'class Solution {
    public int maxArea(int[] height) {
        
    }
}',
'class Solution {
public:
    int maxArea(vector<int>& height) {
        
    }
};',
'[{"input": [[1, 8, 6, 2, 5, 4, 8, 3, 7]], "expectedOutput": 49}, {"input": [[1, 1]], "expectedOutput": 1}, {"input": [[4, 3, 2, 1, 4]], "expectedOutput": 16}]',
'O(n)',
'O(1)');


-- Question 9: 3Sum
-- 3Sum (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(9, 1, '3Sum', 'medium',
'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.

Notice that the solution set must not contain duplicate triplets.',
'["3 <= nums.length <= 3000", "-10^5 <= nums[i] <= 10^5"]',
'[{"input": {"nums": [-1, 0, 1, 2, -1, -4]}, "output": [[-1, -1, 2], [-1, 0, 1]], "explanation": "The distinct triplets are [-1,0,1] and [-1,-1,2]."}, {"input": {"nums": [0, 1, 1]}, "output": [], "explanation": "The only possible triplet does not sum up to 0."}]',
'["array", "two-pointers", "sorting"]',
'["LeetCode URL: https://leetcode.com/problems/3sum/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(9,
'class Solution:
    def threeSum(self, nums: List[int]) -> List[List[int]]:
        pass',
'class Solution {
    public List<List<Integer>> threeSum(int[] nums) {
        
    }
}',
'class Solution {
public:
    vector<vector<int>> threeSum(vector<int>& nums) {
        
    }
};',
'[{"input": [[-1, 0, 1, 2, -1, -4]], "expectedOutput": [[-1, -1, 2], [-1, 0, 1]]}, {"input": [[0, 1, 1]], "expectedOutput": []}, {"input": [[0, 0, 0]], "expectedOutput": [[0, 0, 0]]}]',
'O(n^2)',
'O(1)');


-- Question 10: Group Anagrams
-- Group Anagrams (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(10, 1, 'Group Anagrams', 'medium',
'Given an array of strings strs, group the anagrams together. You can return the answer in any order.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.',
'["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100", "strs[i] consists of lowercase English letters"]',
'[{"input": {"strs": ["eat", "tea", "tan", "ate", "nat", "bat"]}, "output": [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]], "explanation": "Group words that are anagrams."}]',
'["array", "hash-table", "string", "sorting"]',
'["LeetCode URL: https://leetcode.com/problems/group-anagrams/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(10,
'class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        pass',
'class Solution {
    public List<List<String>> groupAnagrams(String[] strs) {
        
    }
}',
'class Solution {
public:
    vector<vector<string>> groupAnagrams(vector<string>& strs) {
        
    }
};',
'[{"input": [["eat", "tea", "tan", "ate", "nat", "bat"]], "expectedOutput": [["bat"], ["nat", "tan"], ["ate", "eat", "tea"]]}, {"input": [[""]], "expectedOutput": [[""]]}, {"input": [["a"]], "expectedOutput": [["a"]]}]',
'O(n*k)',
'O(n*k)');


-- Question 11: Longest Palindromic Substring
-- Longest Palindromic Substring (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(11, 1, 'Longest Palindromic Substring', 'medium',
'Given a string s, return the longest palindromic substring in s.',
'["1 <= s.length <= 1000", "s consist of only digits and English letters"]',
'[{"input": {"s": "babad"}, "output": "bab", "explanation": "Note: ''aba'' is also a valid answer."}, {"input": {"s": "cbbd"}, "output": "bb", "explanation": "The longest palindrome is ''bb''."}]',
'["string", "dynamic-programming"]',
'["LeetCode URL: https://leetcode.com/problems/longest-palindromic-substring/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(11,
'class Solution:
    def longestPalindrome(self, s: str) -> str:
        pass',
'class Solution {
    public String longestPalindrome(String s) {
        
    }
}',
'class Solution {
public:
    string longestPalindrome(string s) {
        
    }
};',
'[{"input": ["babad"], "expectedOutput": "bab"}, {"input": ["cbbd"], "expectedOutput": "bb"}, {"input": ["a"], "expectedOutput": "a"}]',
'O(n^2)',
'O(1)');


-- Question 12: Product of Array Except Self
-- Product of Array Except Self (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(12, 1, 'Product of Array Except Self', 'medium',
'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i].

You must write an algorithm that runs in O(n) time and without using the division operation.',
'["2 <= nums.length <= 10^5", "-30 <= nums[i] <= 30", "The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer"]',
'[{"input": {"nums": [1, 2, 3, 4]}, "output": [24, 12, 8, 6], "explanation": "answer[0] = 2*3*4 = 24, answer[1] = 1*3*4 = 12, etc."}]',
'["array", "prefix-sum"]',
'["LeetCode URL: https://leetcode.com/problems/product-of-array-except-self/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(12,
'class Solution:
    def productExceptSelf(self, nums: List[int]) -> List[int]:
        pass',
'class Solution {
    public int[] productExceptSelf(int[] nums) {
        
    }
}',
'class Solution {
public:
    vector<int> productExceptSelf(vector<int>& nums) {
        
    }
};',
'[{"input": [[1, 2, 3, 4]], "expectedOutput": [24, 12, 8, 6]}, {"input": [[-1, 1, 0, -3, 3]], "expectedOutput": [0, 0, 9, 0, 0]}]',
'O(n)',
'O(1)');


-- Question 13: Spiral Matrix
-- Spiral Matrix (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(13, 1, 'Spiral Matrix', 'medium',
'Given an m x n matrix, return all elements of the matrix in spiral order.',
'["m == matrix.length", "n == matrix[i].length", "1 <= m, n <= 10", "-100 <= matrix[i][j] <= 100"]',
'[{"input": {"matrix": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}, "output": [1, 2, 3, 6, 9, 8, 7, 4, 5], "explanation": "Traverse the matrix in spiral order."}]',
'["array", "matrix", "simulation"]',
'["LeetCode URL: https://leetcode.com/problems/spiral-matrix/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(13,
'class Solution:
    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:
        pass',
'class Solution {
    public List<Integer> spiralOrder(int[][] matrix) {
        
    }
}',
'class Solution {
public:
    vector<int> spiralOrder(vector<vector<int>>& matrix) {
        
    }
};',
'[{"input": [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], "expectedOutput": [1, 2, 3, 6, 9, 8, 7, 4, 5]}, {"input": [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]], "expectedOutput": [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]}]',
'O(m*n)',
'O(1)');


-- Question 14: Rotate Image
-- Rotate Image (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(14, 1, 'Rotate Image', 'medium',
'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly.',
'["n == matrix.length == matrix[i].length", "1 <= n <= 20", "-1000 <= matrix[i][j] <= 1000"]',
'[{"input": {"matrix": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}, "output": [[7, 4, 1], [8, 5, 2], [9, 6, 3]], "explanation": "Rotate 90 degrees clockwise."}]',
'["array", "matrix"]',
'["LeetCode URL: https://leetcode.com/problems/rotate-image/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(14,
'class Solution:
    def rotate(self, matrix: List[List[int]]) -> None:
        pass',
'class Solution {
    public void rotate(int[][] matrix) {
        
    }
}',
'class Solution {
public:
    void rotate(vector<vector<int>>& matrix) {
        
    }
};',
'[{"input": [[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], "expectedOutput": [[7, 4, 1], [8, 5, 2], [9, 6, 3]]}, {"input": [[[5, 1, 9, 11], [2, 4, 8, 10], [13, 3, 6, 7], [15, 14, 12, 16]]], "expectedOutput": [[15, 13, 2, 5], [14, 3, 4, 1], [12, 6, 8, 9], [16, 7, 10, 11]]}]',
'O(n^2)',
'O(1)');


-- Question 15: Set Matrix Zeroes
-- Set Matrix Zeroes (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(15, 1, 'Set Matrix Zeroes', 'medium',
'Given an m x n integer matrix matrix, if an element is 0, set its entire row and column to 0''s.

You must do it in place.',
'["m == matrix.length", "n == matrix[0].length", "1 <= m, n <= 200", "-2^31 <= matrix[i][j] <= 2^31 - 1"]',
'[{"input": {"matrix": [[1, 1, 1], [1, 0, 1], [1, 1, 1]]}, "output": [[1, 0, 1], [0, 0, 0], [1, 0, 1]], "explanation": "Mark row and column of 0s."}]',
'["array", "matrix", "hash-table"]',
'["LeetCode URL: https://leetcode.com/problems/set-matrix-zeroes/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(15,
'class Solution:
    def setZeroes(self, matrix: List[List[int]]) -> None:
        pass',
'class Solution {
    public void setZeroes(int[][] matrix) {
        
    }
}',
'class Solution {
public:
    void setZeroes(vector<vector<int>>& matrix) {
        
    }
};',
'[{"input": [[[1, 1, 1], [1, 0, 1], [1, 1, 1]]], "expectedOutput": [[1, 0, 1], [0, 0, 0], [1, 0, 1]]}, {"input": [[[0, 1, 2, 0], [3, 4, 5, 2], [1, 3, 1, 5]]], "expectedOutput": [[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]]}]',
'O(m*n)',
'O(1)');


-- Question 16: Subarray Sum Equals K
-- Subarray Sum Equals K (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(16, 1, 'Subarray Sum Equals K', 'medium',
'Given an array of integers nums and an integer k, return the total number of subarrays whose sum equals to k.

A subarray is a contiguous non-empty sequence of elements within an array.',
'["1 <= nums.length <= 2 * 10^4", "-1000 <= nums[i] <= 1000", "-10^7 <= k <= 10^7"]',
'[{"input": {"nums": [1, 1, 1], "k": 2}, "output": 2, "explanation": "Subarrays [1,1] and [1,1] sum to 2."}, {"input": {"nums": [1, 2, 3], "k": 3}, "output": 2, "explanation": "Subarrays [1,2] and [3] sum to 3."}]',
'["array", "hash-table", "prefix-sum"]',
'["LeetCode URL: https://leetcode.com/problems/subarray-sum-equals-k/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(16,
'class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        pass',
'class Solution {
    public int subarraySum(int[] nums, int k) {
        
    }
}',
'class Solution {
public:
    int subarraySum(vector<int>& nums, int k) {
        
    }
};',
'[{"input": [[1, 1, 1], 2], "expectedOutput": 2}, {"input": [[1, 2, 3], 3], "expectedOutput": 2}]',
'O(n)',
'O(n)');


-- Question 17: Maximum Subarray
-- Maximum Subarray (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(17, 1, 'Maximum Subarray', 'medium',
'Given an integer array nums, find the subarray with the largest sum, and return its sum.',
'["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"]',
'[{"input": {"nums": [-2, 1, -3, 4, -1, 2, 1, -5, 4]}, "output": 6, "explanation": "The subarray [4,-1,2,1] has the largest sum 6."}, {"input": {"nums": [1]}, "output": 1, "explanation": "The subarray [1] has the largest sum 1."}]',
'["array", "divide-and-conquer", "dynamic-programming"]',
'["LeetCode URL: https://leetcode.com/problems/maximum-subarray/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(17,
'class Solution:
    def maxSubArray(self, nums: List[int]) -> int:
        pass',
'class Solution {
    public int maxSubArray(int[] nums) {
        
    }
}',
'class Solution {
public:
    int maxSubArray(vector<int>& nums) {
        
    }
};',
'[{"input": [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], "expectedOutput": 6}, {"input": [[1]], "expectedOutput": 1}, {"input": [[5, 4, -1, 7, 8]], "expectedOutput": 23}]',
'O(n)',
'O(1)');


-- Question 18: Remove Nth Node From End of List
-- Remove Nth Node From End of List (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(18, 1, 'Remove Nth Node From End of List', 'medium',
'Given the head of a linked list, remove the nth node from the end of the list and return its head.',
'["The number of nodes in the list is sz", "1 <= sz <= 30", "0 <= Node.val <= 100", "1 <= n <= sz"]',
'[{"input": {"head": [1, 2, 3, 4, 5], "n": 2}, "output": [1, 2, 3, 5], "explanation": "Remove 2nd node from end."}]',
'["linked-list", "two-pointers"]',
'["LeetCode URL: https://leetcode.com/problems/remove-nth-node-from-end-of-list/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(18,
'class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        pass',
'class Solution {
    public ListNode removeNthFromEnd(ListNode head, int n) {
        
    }
}',
'class Solution {
public:
    ListNode* removeNthFromEnd(ListNode* head, int n) {
        
    }
};',
'[{"input": [[1, 2, 3, 4, 5], 2], "expectedOutput": [1, 2, 3, 5]}, {"input": [[1], 1], "expectedOutput": []}, {"input": [[1, 2], 1], "expectedOutput": [1]}]',
'O(n)',
'O(1)');


-- Question 19: Reverse Linked List II
-- Reverse Linked List II (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(19, 1, 'Reverse Linked List II', 'medium',
'Given the head of a singly linked list and two integers left and right where left <= right, reverse the nodes of the list from position left to position right, and return the reversed list.',
'["The number of nodes in the list is n", "1 <= n <= 500", "-500 <= Node.val <= 500", "1 <= left <= right <= n"]',
'[{"input": {"head": [1, 2, 3, 4, 5], "left": 2, "right": 4}, "output": [1, 4, 3, 2, 5], "explanation": "Reverse nodes from position 2 to 4."}]',
'["linked-list"]',
'["LeetCode URL: https://leetcode.com/problems/reverse-linked-list-ii/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(19,
'class Solution:
    def reverseBetween(self, head: Optional[ListNode], left: int, right: int) -> Optional[ListNode]:
        pass',
'class Solution {
    public ListNode reverseBetween(ListNode head, int left, int right) {
        
    }
}',
'class Solution {
public:
    ListNode* reverseBetween(ListNode* head, int left, int right) {
        
    }
};',
'[{"input": [[1, 2, 3, 4, 5], 2, 4], "expectedOutput": [1, 4, 3, 2, 5]}, {"input": [[5], 1, 1], "expectedOutput": [5]}]',
'O(n)',
'O(1)');


-- Question 20: Swap Nodes in Pairs
-- Swap Nodes in Pairs (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(20, 1, 'Swap Nodes in Pairs', 'medium',
'Given a linked list, swap every two adjacent nodes and return its head. You must solve the problem without modifying the values in the list''s nodes.',
'["The number of nodes in the list is in the range [0, 100]", "0 <= Node.val <= 100"]',
'[{"input": {"head": [1, 2, 3, 4]}, "output": [2, 1, 4, 3], "explanation": "Swap adjacent pairs."}]',
'["linked-list", "recursion"]',
'["LeetCode URL: https://leetcode.com/problems/swap-nodes-in-pairs/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(20,
'class Solution:
    def swapPairs(self, head: Optional[ListNode]) -> Optional[ListNode]:
        pass',
'class Solution {
    public ListNode swapPairs(ListNode head) {
        
    }
}',
'class Solution {
public:
    ListNode* swapPairs(ListNode* head) {
        
    }
};',
'[{"input": [[1, 2, 3, 4]], "expectedOutput": [2, 1, 4, 3]}, {"input": [[]], "expectedOutput": []}, {"input": [[1]], "expectedOutput": [1]}]',
'O(n)',
'O(1)');


-- Question 21: Binary Tree Level Order Traversal
-- Binary Tree Level Order Traversal (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(21, 1, 'Binary Tree Level Order Traversal', 'medium',
'Given the root of a binary tree, return the level order traversal of its nodes'' values. (i.e., from left to right, level by level).',
'["The number of nodes in the tree is in the range [0, 2000]", "-1000 <= Node.val <= 1000"]',
'[{"input": {"root": [3, 9, 20, null, null, 15, 7]}, "output": [[3], [9, 20], [15, 7]], "explanation": "Level by level traversal."}]',
'["tree", "breadth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/binary-tree-level-order-traversal/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(21,
'class Solution:
    def levelOrder(self, root: Optional[TreeNode]) -> List[List[int]]:
        pass',
'class Solution {
    public List<List<Integer>> levelOrder(TreeNode root) {
        
    }
}',
'class Solution {
public:
    vector<vector<int>> levelOrder(TreeNode* root) {
        
    }
};',
'[{"input": [[3, 9, 20, null, null, 15, 7]], "expectedOutput": [[3], [9, 20], [15, 7]]}, {"input": [[1]], "expectedOutput": [[1]]}, {"input": [[]], "expectedOutput": []}]',
'O(n)',
'O(n)');


-- Question 22: Validate Binary Search Tree
-- Validate Binary Search Tree (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(22, 1, 'Validate Binary Search Tree', 'medium',
'Given the root of a binary tree, determine if it is a valid binary search tree (BST).

A valid BST is defined as follows:
- The left subtree of a node contains only nodes with keys less than the node''s key.
- The right subtree of a node contains only nodes with keys greater than the node''s key.
- Both the left and right subtrees must also be binary search trees.',
'["The number of nodes in the tree is in the range [1, 10^4]", "-2^31 <= Node.val <= 2^31 - 1"]',
'[{"input": {"root": [2, 1, 3]}, "output": true, "explanation": "Valid BST."}, {"input": {"root": [5, 1, 4, null, null, 3, 6]}, "output": false, "explanation": "Node 4 in right subtree of 5 violates BST property."}]',
'["tree", "depth-first-search", "binary-search-tree"]',
'["LeetCode URL: https://leetcode.com/problems/validate-binary-search-tree/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(22,
'class Solution:
    def isValidBST(self, root: Optional[TreeNode]) -> bool:
        pass',
'class Solution {
    public boolean isValidBST(TreeNode root) {
        
    }
}',
'class Solution {
public:
    bool isValidBST(TreeNode* root) {
        
    }
};',
'[{"input": [[2, 1, 3]], "expectedOutput": true}, {"input": [[5, 1, 4, null, null, 3, 6]], "expectedOutput": false}]',
'O(n)',
'O(n)');


-- Question 23: Kth Smallest Element in a BST
-- Kth Smallest Element in a BST (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(23, 1, 'Kth Smallest Element in a BST', 'medium',
'Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.',
'["The number of nodes in the tree is n", "1 <= k <= n <= 10^4", "0 <= Node.val <= 10^4"]',
'[{"input": {"root": [3, 1, 4, null, 2], "k": 1}, "output": 1, "explanation": "The smallest element is 1."}, {"input": {"root": [5, 3, 6, 2, 4, null, null, 1], "k": 3}, "output": 3, "explanation": "The 3rd smallest is 3."}]',
'["tree", "depth-first-search", "binary-search-tree"]',
'["LeetCode URL: https://leetcode.com/problems/kth-smallest-element-in-a-bst/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(23,
'class Solution:
    def kthSmallest(self, root: Optional[TreeNode], k: int) -> int:
        pass',
'class Solution {
    public int kthSmallest(TreeNode root, int k) {
        
    }
}',
'class Solution {
public:
    int kthSmallest(TreeNode* root, int k) {
        
    }
};',
'[{"input": [[3, 1, 4, null, 2], 1], "expectedOutput": 1}, {"input": [[5, 3, 6, 2, 4, null, null, 1], 3], "expectedOutput": 3}]',
'O(n)',
'O(n)');


-- Question 24: Binary Tree Right Side View
-- Binary Tree Right Side View (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(24, 1, 'Binary Tree Right Side View', 'medium',
'Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.',
'["The number of nodes in the tree is in the range [0, 100]", "-100 <= Node.val <= 100"]',
'[{"input": {"root": [1, 2, 3, null, 5, null, 4]}, "output": [1, 3, 4], "explanation": "Right side view shows nodes 1, 3, 4."}]',
'["tree", "depth-first-search", "breadth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/binary-tree-right-side-view/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(24,
'class Solution:
    def rightSideView(self, root: Optional[TreeNode]) -> List[int]:
        pass',
'class Solution {
    public List<Integer> rightSideView(TreeNode root) {
        
    }
}',
'class Solution {
public:
    vector<int> rightSideView(TreeNode* root) {
        
    }
};',
'[{"input": [[1, 2, 3, null, 5, null, 4]], "expectedOutput": [1, 3, 4]}, {"input": [[1, null, 3]], "expectedOutput": [1, 3]}, {"input": [[]], "expectedOutput": []}]',
'O(n)',
'O(n)');


-- Question 25: Path Sum II
-- Path Sum II (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(25, 1, 'Path Sum II', 'medium',
'Given the root of a binary tree and an integer targetSum, return all root-to-leaf paths where the sum of the node values in the path equals targetSum. Each path should be returned as a list of the node values, not node references.

A root-to-leaf path is a path starting from the root and ending at any leaf node.',
'["The number of nodes in the tree is in the range [0, 5000]", "-1000 <= Node.val <= 1000", "-1000 <= targetSum <= 1000"]',
'[{"input": {"root": [5, 4, 8, 11, null, 13, 4, 7, 2, null, null, 5, 1], "targetSum": 22}, "output": [[5, 4, 11, 2], [5, 8, 4, 5]], "explanation": "Two paths sum to 22."}]',
'["tree", "backtracking", "depth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/path-sum-ii/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(25,
'class Solution:
    def pathSum(self, root: Optional[TreeNode], targetSum: int) -> List[List[int]]:
        pass',
'class Solution {
    public List<List<Integer>> pathSum(TreeNode root, int targetSum) {
        
    }
}',
'class Solution {
public:
    vector<vector<int>> pathSum(TreeNode* root, int targetSum) {
        
    }
};',
'[{"input": [[5, 4, 8, 11, null, 13, 4, 7, 2, null, null, 5, 1], 22], "expectedOutput": [[5, 4, 11, 2], [5, 8, 4, 5]]}, {"input": [[1, 2, 3], 5], "expectedOutput": []}, {"input": [[1, 2], 0], "expectedOutput": []}]',
'O(n^2)',
'O(n)');


-- Question 26: Construct Binary Tree from Preorder and Inorder Traversal
-- Construct Binary Tree from Preorder and Inorder Traversal (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(26, 1, 'Construct Binary Tree from Preorder and Inorder Traversal', 'medium',
'Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.',
'["1 <= preorder.length <= 3000", "inorder.length == preorder.length", "-3000 <= preorder[i], inorder[i] <= 3000", "preorder and inorder consist of unique values"]',
'[{"input": {"preorder": [3, 9, 20, 15, 7], "inorder": [9, 3, 15, 20, 7]}, "output": [3, 9, 20, null, null, 15, 7], "explanation": "Construct tree from traversals."}]',
'["tree", "array", "hash-table", "divide-and-conquer"]',
'["LeetCode URL: https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(26,
'class Solution:
    def buildTree(self, preorder: List[int], inorder: List[int]) -> Optional[TreeNode]:
        pass',
'class Solution {
    public TreeNode buildTree(int[] preorder, int[] inorder) {
        
    }
}',
'class Solution {
public:
    TreeNode* buildTree(vector<int>& preorder, vector<int>& inorder) {
        
    }
};',
'[{"input": [[3, 9, 20, 15, 7], [9, 3, 15, 20, 7]], "expectedOutput": [3, 9, 20, null, null, 15, 7]}, {"input": [[-1], [-1]], "expectedOutput": [-1]}]',
'O(n)',
'O(n)');


-- Question 27: Lowest Common Ancestor of a Binary Tree
-- Lowest Common Ancestor of a Binary Tree (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(27, 1, 'Lowest Common Ancestor of a Binary Tree', 'medium',
'Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.

The lowest common ancestor is defined as the lowest node in the tree that has both p and q as descendants (where we allow a node to be a descendant of itself).',
'["The number of nodes in the tree is in the range [2, 10^5]", "-10^9 <= Node.val <= 10^9", "All Node.val are unique", "p != q", "p and q exist in the tree"]',
'[{"input": {"root": [3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], "p": 5, "q": 1}, "output": 3, "explanation": "The LCA of nodes 5 and 1 is 3."}]',
'["tree", "depth-first-search", "binary-tree"]',
'["LeetCode URL: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(27,
'class Solution:
    def lowestCommonAncestor(self, root: TreeNode, p: TreeNode, q: TreeNode) -> TreeNode:
        pass',
'class Solution {
    public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {
        
    }
}',
'class Solution {
public:
    TreeNode* lowestCommonAncestor(TreeNode* root, TreeNode* p, TreeNode* q) {
        
    }
};',
'[{"input": [[3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], 5, 1], "expectedOutput": 3}, {"input": [[3, 5, 1, 6, 2, 0, 8, null, null, 7, 4], 5, 4], "expectedOutput": 5}]',
'O(n)',
'O(n)');


-- Question 28: Number of Islands
-- Number of Islands (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(28, 1, 'Number of Islands', 'medium',
'Given an m x n 2D binary grid which represents a map of ''1''s (land) and ''0''s (water), return the number of islands.

An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.',
'["m == grid.length", "n == grid[i].length", "1 <= m, n <= 300", "grid[i][j] is ''0'' or ''1''"]',
'[{"input": {"grid": [["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]}, "output": 1, "explanation": "One connected island."}]',
'["array", "depth-first-search", "breadth-first-search", "union-find", "matrix"]',
'["LeetCode URL: https://leetcode.com/problems/number-of-islands/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(28,
'class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        pass',
'class Solution {
    public int numIslands(char[][] grid) {
        
    }
}',
'class Solution {
public:
    int numIslands(vector<vector<char>>& grid) {
        
    }
};',
'[{"input": [[["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]], "expectedOutput": 1}, {"input": [[["1", "1", "0", "0", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "1", "0", "0"], ["0", "0", "0", "1", "1"]]], "expectedOutput": 3}]',
'O(m*n)',
'O(m*n)');


-- Question 29: Course Schedule
-- Course Schedule (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(29, 1, 'Course Schedule', 'medium',
'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai.

Return true if you can finish all courses. Otherwise, return false.',
'["1 <= numCourses <= 2000", "0 <= prerequisites.length <= 5000", "prerequisites[i].length == 2", "0 <= ai, bi < numCourses", "All the pairs prerequisites[i] are unique"]',
'[{"input": {"numCourses": 2, "prerequisites": [[1, 0]]}, "output": true, "explanation": "Take course 0 first, then course 1."}, {"input": {"numCourses": 2, "prerequisites": [[1, 0], [0, 1]]}, "output": false, "explanation": "Circular dependency."}]',
'["graph", "topological-sort", "depth-first-search", "breadth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/course-schedule/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(29,
'class Solution:
    def canFinish(self, numCourses: int, prerequisites: List[List[int]]) -> bool:
        pass',
'class Solution {
    public boolean canFinish(int numCourses, int[][] prerequisites) {
        
    }
}',
'class Solution {
public:
    bool canFinish(int numCourses, vector<vector<int>>& prerequisites) {
        
    }
};',
'[{"input": [2, [[1, 0]]], "expectedOutput": true}, {"input": [2, [[1, 0], [0, 1]]], "expectedOutput": false}]',
'O(V+E)',
'O(V+E)');


-- Question 30: Clone Graph
-- Clone Graph (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(30, 1, 'Clone Graph', 'medium',
'Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph.

Each node in the graph contains a value (int) and a list (List[Node]) of its neighbors.',
'["The number of nodes in the graph is in the range [0, 100]", "1 <= Node.val <= 100", "Node.val is unique for each node", "There are no repeated edges and no self-loops"]',
'[{"input": {"adjList": [[2, 4], [1, 3], [2, 4], [1, 3]]}, "output": [[2, 4], [1, 3], [2, 4], [1, 3]], "explanation": "Clone the graph."}]',
'["hash-table", "depth-first-search", "breadth-first-search", "graph"]',
'["LeetCode URL: https://leetcode.com/problems/clone-graph/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(30,
'class Solution:
    def cloneGraph(self, node: Optional[''Node'']) -> Optional[''Node'']:
        pass',
'class Solution {
    public Node cloneGraph(Node node) {
        
    }
}',
'class Solution {
public:
    Node* cloneGraph(Node* node) {
        
    }
};',
'[{"input": [[[2, 4], [1, 3], [2, 4], [1, 3]]], "expectedOutput": [[2, 4], [1, 3], [2, 4], [1, 3]]}, {"input": [[[]]], "expectedOutput": [[]]}, {"input": [[]], "expectedOutput": []}]',
'O(N+M)',
'O(N)');


-- Question 31: Word Search
-- Word Search (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(31, 1, 'Word Search', 'medium',
'Given an m x n grid of characters board and a string word, return true if word exists in the grid.

The word can be constructed from letters of sequentially adjacent cells, where adjacent cells are horizontally or vertically neighboring.',
'["m == board.length", "n = board[i].length", "1 <= m, n <= 6", "1 <= word.length <= 15", "board and word consists of only lowercase and uppercase English letters"]',
'[{"input": {"board": [["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "word": "ABCCED"}, "output": true, "explanation": "Word found in board."}]',
'["array", "backtracking", "matrix"]',
'["LeetCode URL: https://leetcode.com/problems/word-search/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(31,
'class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:
        pass',
'class Solution {
    public boolean exist(char[][] board, String word) {
        
    }
}',
'class Solution {
public:
    bool exist(vector<vector<char>>& board, string word) {
        
    }
};',
'[{"input": [[["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "ABCCED"], "expectedOutput": true}, {"input": [[["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "SEE"], "expectedOutput": true}, {"input": [[["A", "B", "C", "E"], ["S", "F", "C", "S"], ["A", "D", "E", "E"]], "ABCB"], "expectedOutput": false}]',
'O(m*n*4^L)',
'O(L)');


-- Question 32: Coin Change
-- Coin Change (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(32, 1, 'Coin Change', 'medium',
'You are given an integer array coins representing coins of different denominations and an integer amount representing a total amount of money.

Return the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.',
'["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"]',
'[{"input": {"coins": [1, 2, 5], "amount": 11}, "output": 3, "explanation": "11 = 5 + 5 + 1"}, {"input": {"coins": [2], "amount": 3}, "output": -1, "explanation": "Cannot make amount 3."}]',
'["array", "dynamic-programming", "breadth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/coin-change/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(32,
'class Solution:
    def coinChange(self, coins: List[int], amount: int) -> int:
        pass',
'class Solution {
    public int coinChange(int[] coins, int amount) {
        
    }
}',
'class Solution {
public:
    int coinChange(vector<int>& coins, int amount) {
        
    }
};',
'[{"input": [[1, 2, 5], 11], "expectedOutput": 3}, {"input": [[2], 3], "expectedOutput": -1}, {"input": [[1], 0], "expectedOutput": 0}]',
'O(amount * n)',
'O(amount)');


-- Question 33: Trapping Rain Water
-- Trapping Rain Water (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(33, 1, 'Trapping Rain Water', 'hard',
'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
'["n == height.length", "1 <= n <= 2 * 10^4", "0 <= height[i] <= 10^5"]',
'[{"input": {"height": [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]}, "output": 6, "explanation": "The elevation map can trap 6 units of rain water."}]',
'["array", "two-pointers", "dynamic-programming", "stack", "monotonic-stack"]',
'["LeetCode URL: https://leetcode.com/problems/trapping-rain-water/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(33,
'class Solution:
    def trap(self, height: List[int]) -> int:
        pass',
'class Solution {
    public int trap(int[] height) {
        
    }
}',
'class Solution {
public:
    int trap(vector<int>& height) {
        
    }
};',
'[{"input": [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], "expectedOutput": 6}, {"input": [[4, 2, 0, 3, 2, 5]], "expectedOutput": 9}]',
'O(n)',
'O(1)');


-- Question 34: Median of Two Sorted Arrays
-- Median of Two Sorted Arrays (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(34, 1, 'Median of Two Sorted Arrays', 'hard',
'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).',
'["nums1.length == m", "nums2.length == n", "0 <= m <= 1000", "0 <= n <= 1000", "1 <= m + n <= 2000", "-10^6 <= nums1[i], nums2[i] <= 10^6"]',
'[{"input": {"nums1": [1, 3], "nums2": [2]}, "output": 2.0, "explanation": "Merged array = [1,2,3], median = 2."}, {"input": {"nums1": [1, 2], "nums2": [3, 4]}, "output": 2.5, "explanation": "Merged array = [1,2,3,4], median = (2+3)/2 = 2.5."}]',
'["array", "binary-search", "divide-and-conquer"]',
'["LeetCode URL: https://leetcode.com/problems/median-of-two-sorted-arrays/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(34,
'class Solution:
    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:
        pass',
'class Solution {
    public double findMedianSortedArrays(int[] nums1, int[] nums2) {
        
    }
}',
'class Solution {
public:
    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {
        
    }
};',
'[{"input": [[1, 3], [2]], "expectedOutput": 2.0}, {"input": [[1, 2], [3, 4]], "expectedOutput": 2.5}]',
'O(log(min(m,n)))',
'O(1)');


-- Question 35: Binary Tree Maximum Path Sum
-- Binary Tree Maximum Path Sum (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(35, 1, 'Binary Tree Maximum Path Sum', 'hard',
'A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root.

The path sum of a path is the sum of the node''s values in the path.

Given the root of a binary tree, return the maximum path sum of any non-empty path.',
'["The number of nodes in the tree is in the range [1, 3 * 10^4]", "-1000 <= Node.val <= 1000"]',
'[{"input": {"root": [1, 2, 3]}, "output": 6, "explanation": "The optimal path is 2 -> 1 -> 3 with a path sum of 2 + 1 + 3 = 6."}, {"input": {"root": [-10, 9, 20, null, null, 15, 7]}, "output": 42, "explanation": "The optimal path is 15 -> 20 -> 7 with a path sum of 15 + 20 + 7 = 42."}]',
'["tree", "depth-first-search", "dynamic-programming", "binary-tree"]',
'["LeetCode URL: https://leetcode.com/problems/binary-tree-maximum-path-sum/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(35,
'class Solution:
    def maxPathSum(self, root: Optional[TreeNode]) -> int:
        pass',
'class Solution {
    public int maxPathSum(TreeNode root) {
        
    }
}',
'class Solution {
public:
    int maxPathSum(TreeNode* root) {
        
    }
};',
'[{"input": [[1, 2, 3]], "expectedOutput": 6}, {"input": [[-10, 9, 20, null, null, 15, 7]], "expectedOutput": 42}]',
'O(n)',
'O(h)');


-- Question 36: Serialize and Deserialize Binary Tree
-- Serialize and Deserialize Binary Tree (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(36, 1, 'Serialize and Deserialize Binary Tree', 'hard',
'Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer, or transmitted across a network connection link to be reconstructed later in the same or another computer environment.

Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work.',
'["The number of nodes in the tree is in the range [0, 10^4]", "-1000 <= Node.val <= 1000"]',
'[{"input": {"root": [1, 2, 3, null, null, 4, 5]}, "output": [1, 2, 3, null, null, 4, 5], "explanation": "Serialize then deserialize the tree."}]',
'["string", "tree", "depth-first-search", "breadth-first-search", "design", "binary-tree"]',
'["LeetCode URL: https://leetcode.com/problems/serialize-and-deserialize-binary-tree/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(36,
'class Codec:
    def serialize(self, root: Optional[TreeNode]) -> str:
        pass
    
    def deserialize(self, data: str) -> Optional[TreeNode]:
        pass',
'public class Codec {
    public String serialize(TreeNode root) {
        
    }
    
    public TreeNode deserialize(String data) {
        
    }
}',
'class Codec {
public:
    string serialize(TreeNode* root) {
        
    }
    
    TreeNode* deserialize(string data) {
        
    }
};',
'[{"input": [[1, 2, 3, null, null, 4, 5]], "expectedOutput": [1, 2, 3, null, null, 4, 5]}, {"input": [[]], "expectedOutput": []}]',
'O(n)',
'O(n)');


-- Question 37: Regular Expression Matching
-- Regular Expression Matching (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(37, 1, 'Regular Expression Matching', 'hard',
'Given an input string s and a pattern p, implement regular expression matching with support for ''.'' and ''*'' where:

''.'' Matches any single character.
''*'' Matches zero or more of the preceding element.

The matching should cover the entire input string (not partial).',
'["1 <= s.length <= 20", "1 <= p.length <= 20", "s contains only lowercase English letters", "p contains only lowercase English letters, ''.'', and ''*''"]',
'[{"input": {"s": "aa", "p": "a"}, "output": false, "explanation": "a does not match the entire string aa."}, {"input": {"s": "aa", "p": "a*"}, "output": true, "explanation": "* means zero or more of the preceding element, a. Therefore, by repeating a once, it becomes aa."}]',
'["string", "dynamic-programming", "recursion"]',
'["LeetCode URL: https://leetcode.com/problems/regular-expression-matching/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(37,
'class Solution:
    def isMatch(self, s: str, p: str) -> bool:
        pass',
'class Solution {
    public boolean isMatch(String s, String p) {
        
    }
}',
'class Solution {
public:
    bool isMatch(string s, string p) {
        
    }
};',
'[{"input": ["aa", "a"], "expectedOutput": false}, {"input": ["aa", "a*"], "expectedOutput": true}, {"input": ["ab", ".*"], "expectedOutput": true}]',
'O(m*n)',
'O(m*n)');


-- Question 38: Edit Distance
-- Edit Distance (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(38, 1, 'Edit Distance', 'hard',
'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.

You have the following three operations permitted on a word:
- Insert a character
- Delete a character
- Replace a character',
'["0 <= word1.length, word2.length <= 500", "word1 and word2 consist of lowercase English letters"]',
'[{"input": {"word1": "horse", "word2": "ros"}, "output": 3, "explanation": "horse -> rorse (replace ''h'' with ''r'') -> rose (remove ''r'') -> ros (remove ''e'')"}, {"input": {"word1": "intention", "word2": "execution"}, "output": 5, "explanation": "intention -> inention (remove ''t'') -> enention (replace ''i'' with ''e'') -> exention (replace ''n'' with ''x'') -> exection (replace ''n'' with ''c'') -> execution (insert ''u'')"}]',
'["string", "dynamic-programming"]',
'["LeetCode URL: https://leetcode.com/problems/edit-distance/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(38,
'class Solution:
    def minDistance(self, word1: str, word2: str) -> int:
        pass',
'class Solution {
    public int minDistance(String word1, String word2) {
        
    }
}',
'class Solution {
public:
    int minDistance(string word1, string word2) {
        
    }
};',
'[{"input": ["horse", "ros"], "expectedOutput": 3}, {"input": ["intention", "execution"], "expectedOutput": 5}]',
'O(m*n)',
'O(m*n)');


-- Question 39: Word Ladder
-- Word Ladder (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(39, 1, 'Word Ladder', 'hard',
'A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that:
- Every adjacent pair of words differs by a single letter.
- Every si for 1 <= i <= k is in wordList. Note that beginWord does not need to be in wordList.
- sk == endWord

Given two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord, or 0 if no such sequence exists.',
'["1 <= beginWord.length <= 10", "endWord.length == beginWord.length", "1 <= wordList.length <= 5000", "wordList[i].length == beginWord.length", "All strings consist of lowercase English letters", "beginWord != endWord", "All the words in wordList are unique"]',
'[{"input": {"beginWord": "hit", "endWord": "cog", "wordList": ["hot", "dot", "dog", "lot", "log", "cog"]}, "output": 5, "explanation": "One shortest transformation sequence is ''hit'' -> ''hot'' -> ''dot'' -> ''dog'' -> ''cog'', which is 5 words long."}, {"input": {"beginWord": "hit", "endWord": "cog", "wordList": ["hot", "dot", "dog", "lot", "log"]}, "output": 0, "explanation": "The endWord ''cog'' is not in wordList, therefore there is no valid transformation sequence."}]',
'["hash-table", "string", "breadth-first-search"]',
'["LeetCode URL: https://leetcode.com/problems/word-ladder/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(39,
'class Solution:
    def ladderLength(self, beginWord: str, endWord: str, wordList: List[str]) -> int:
        pass',
'class Solution {
    public int ladderLength(String beginWord, String endWord, List<String> wordList) {
        
    }
}',
'class Solution {
public:
    int ladderLength(string beginWord, string endWord, vector<string>& wordList) {
        
    }
};',
'[{"input": ["hit", "cog", ["hot", "dot", "dog", "lot", "log", "cog"]], "expectedOutput": 5}, {"input": ["hit", "cog", ["hot", "dot", "dog", "lot", "log"]], "expectedOutput": 0}]',
'O(M^2 * N)',
'O(M^2 * N)');


-- Question 40: Merge k Sorted Lists
-- Merge k Sorted Lists (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
(40, 1, 'Merge k Sorted Lists', 'hard',
'You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.

Merge all the linked-lists into one sorted linked-list and return it.',
'["k == lists.length", "0 <= k <= 10^4", "0 <= lists[i].length <= 500", "-10^4 <= lists[i][j] <= 10^4", "lists[i] is sorted in ascending order", "The sum of lists[i].length will not exceed 10^4"]',
'[{"input": {"lists": [[1, 4, 5], [1, 3, 4], [2, 6]]}, "output": [1, 1, 2, 3, 4, 4, 5, 6], "explanation": "Merging all lists: [1,4,5], [1,3,4], and [2,6] into one sorted list."}, {"input": {"lists": []}, "output": [], "explanation": "Empty input."}, {"input": {"lists": [[]]}, "output": [], "explanation": "Single empty list."}]',
'["linked-list", "divide-and-conquer", "heap", "merge-sort"]',
'["LeetCode URL: https://leetcode.com/problems/merge-k-sorted-lists/"]');

INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
(40,
'class Solution:
    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:
        pass',
'class Solution {
    public ListNode mergeKLists(ListNode[] lists) {
        
    }
}',
'class Solution {
public:
    ListNode* mergeKLists(vector<ListNode*>& lists) {
        
    }
};',
'[{"input": [[[1, 4, 5], [1, 3, 4], [2, 6]]], "expectedOutput": [1, 1, 2, 3, 4, 4, 5, 6]}, {"input": [[]], "expectedOutput": []}, {"input": [[[]]], "expectedOutput": []}]',
'O(N log k) where N is total number of nodes',
'O(k) for heap or O(log k) for divide-and-conquer');



-- ============================================
-- ML SYSTEM DESIGN QUESTIONS
-- ============================================

-- Question 41: Design Facebook News Feed Ranking System
-- Design Facebook News Feed Ranking System (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(41, 2, 'Design Facebook News Feed Ranking System', 'hard',
'Design the ML ranking system for Facebook''s News Feed that serves 3B+ users, deciding which posts to show and in what order to maximize meaningful user engagement.',
'["ranking", "multi-task-learning", "news-feed", "meta", "scale", "personalization"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(41,
'Facebook''s News Feed is the core product serving 3B+ users daily. The ML system must:
- Rank posts from friends, pages, groups, and ads
- Process millions of candidate posts per user
- Predict multiple engagement types (likes, comments, shares, time spent, hide/report)
- Optimize for "meaningful social interactions" not just clicks
- Handle diverse content types (text, photo, video, link, live)
- Serve feeds in <500ms while making complex ML predictions
- Combat engagement bait, clickbait, and misinformation
- Balance organic content with ads (revenue optimization)

The system processes billions of posts daily, makes trillions of predictions, and directly impacts Meta''s $100B+ revenue.',
'["Rank feeds for 3B+ users in real-time (<500ms latency)", "Multi-task prediction: likes, comments, shares, time spent, hide", "Multi-objective optimization (engagement + quality + revenue)", "Handle multiple content types with different engagement patterns", "Lightweight models for edge devices (mobile)", "Feature freshness (recent interactions matter)", "Virality modeling (predict shares/spread)", "Counter-abuse: clickbait, engagement bait, misinformation", "Personalization at scale with privacy constraints", "Seamless A/B testing infrastructure"]',
'{"architecture": "Two-stage: candidate generation + heavy ranking", "model_design": "Multi-task learning for different engagement types", "feature_engineering": "User features, post features, social graph, temporal", "training_pipeline": "Distributed training, online learning", "serving_infra": "Low-latency prediction serving at scale", "multi_objective": "Balancing engagement, quality, revenue, user satisfaction", "counter_abuse": "Strategies to detect and demote low-quality content", "evaluation": "Online metrics (time spent, DAU), offline metrics (AUC, calibration)"}',
'["Candidate Generation (filter from millions to thousands)", "Heavy Ranker (GBDT or Deep Neural Network)", "Multi-task Head (predict likes, comments, shares, time, hide)", "Post-ranking Filters (diversity, freshness, ads insertion)", "Real-time Feature Store", "Online Learning Pipeline", "Counter-abuse Models (clickbait, misinformation)", "A/B Testing Platform", "Metrics Dashboard (time spent, meaningful interactions)"]');


-- Question 42: Design Instagram Reels Recommendation System
-- Design Instagram Reels Recommendation System (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(42, 2, 'Design Instagram Reels Recommendation System', 'hard',
'Design the ML system powering Instagram Reels recommendations - a TikTok competitor serving short-form video to 2B+ users with multi-modal understanding.',
'["recommendation", "multi-modal", "video", "meta", "instagram", "reels", "cold-start"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(42,
'Instagram Reels competes with TikTok by recommending engaging short-form videos. The system must:
- Understand video content (visual, audio, text, music)
- Cold start: recommend videos to new users and new videos to users
- Optimize for watch time and completion rate
- Handle the "creator economy" (help creators grow)
- Prevent filter bubbles while maximizing engagement
- Support audio trends (viral sounds)
- Real-time: new videos should surface quickly
- Multi-modal: video, audio, captions, hashtags, music

Key challenge: Unlike Feed (friends/following), Reels is discovery-based like TikTok.',
'["Multi-modal understanding (video, audio, text, music)", "Real-time recommendations (<100ms)", "Cold start for new users and new content", "Optimize for watch time and completion rate", "Surface trending content quickly (viral detection)", "Creator growth (help small creators get discovered)", "Audio-based features (trending sounds)", "Prevent filter bubbles (content diversity)", "Handle billions of videos", "Mobile-first (lightweight models)"]',
'{"multi_modal": "How video, audio, text signals are combined", "cold_start": "Strategy for new users and new content", "viral_detection": "Identifying trending content early", "model_architecture": "Two-tower, transformers, or hybrid approach", "feature_engineering": "Video embeddings, audio features, engagement signals", "training": "Handling data skew (power law distribution)", "serving": "Low-latency multi-modal inference", "metrics": "Watch time, completion rate, user retention"}',
'["Video Understanding (frame-level embeddings)", "Audio Understanding (music/sound embeddings)", "Text Understanding (captions, hashtags)", "Two-Tower Model (user tower + video tower)", "Candidate Retrieval (ANN search)", "Ranking Model (watch time prediction)", "Trending Detection System", "Creator Recommendation Engine", "Real-time Feature Pipeline", "A/B Testing for Reels"]');


-- Question 43: Design Real-time Ad Targeting & Ranking System
-- Design Real-time Ad Targeting & Ranking System (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(43, 2, 'Design Real-time Ad Targeting & Ranking System', 'hard',
'Design Meta''s ad targeting and ranking system that serves personalized ads to 3B+ users, generating $100B+ annual revenue while balancing user experience.',
'["ads", "ranking", "auction", "revenue", "meta", "ctr-prediction", "conversion"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(43,
'Meta''s ad system is critical infrastructure generating $100B+ revenue. The ML system must:
- Target: Find right users for each ad campaign (audience selection)
- Rank: Order ads by expected value (bid × pCTR × pConversion)
- Auction: Run real-time ad auction for each impression
- Budget: Manage advertiser budgets and pacing
- Quality: Maintain user experience (not too many ads)
- Privacy: Work with limited data (iOS privacy, GDPR)
- Scale: Billions of users, millions of advertisers, trillions of impressions

Revenue equation: eCPM = bid × pCTR × pConversion
Goal: Maximize revenue while maintaining user satisfaction.',
'["Real-time ad auction (<50ms per impression)", "Predict CTR (click-through rate)", "Predict conversion probability", "Budget pacing (spend advertiser budgets evenly)", "Audience targeting (find right users for ads)", "Frequency capping (don''t show same ad too much)", "Ad quality scoring (prevent low-quality ads)", "Privacy-preserving (limited tracking)", "Handle billions of users, millions of advertisers", "Revenue optimization vs user experience"]',
'{"auction_mechanism": "Second-price auction, VCG, or generalized second price", "pCTR_model": "Model for click prediction", "pConversion_model": "Model for conversion prediction", "targeting": "How to match ads to users", "budget_pacing": "Algorithm to spend budgets over time", "calibration": "Are predicted probabilities accurate?", "privacy": "How to work with limited data", "revenue_metrics": "eCPM, revenue lift, advertiser ROI"}',
'["Ad Retrieval (find candidate ads)", "CTR Prediction Model", "Conversion Prediction Model", "Ad Auction System", "Budget Pacing Algorithm", "Frequency Capping", "Ad Quality Classifier", "Targeting Engine (lookalike audiences)", "Attribution System (track conversions)", "Real-time Bidding Infrastructure"]');


-- Question 44: Design AI Content Moderation System for Meta
-- Design AI Content Moderation System for Meta (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(44, 2, 'Design AI Content Moderation System for Meta', 'hard',
'Design Meta''s content moderation system that detects and removes harmful content (hate speech, violence, spam, misinformation) across Facebook, Instagram, WhatsApp at scale.',
'["content-moderation", "classification", "multi-modal", "safety", "meta", "nlp", "computer-vision"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(44,
'Meta''s content moderation is critical for platform safety. The system must:
- Detect multiple violation types: hate speech, violence, nudity, spam, misinformation, bullying
- Multi-modal: text, images, videos, audio
- Real-time: flag content within seconds
- Multi-language: 100+ languages
- Precision is critical: false positives remove legitimate content
- Recall is critical: false negatives allow harmful content
- Human review: queue borderline content for human moderators
- Adversarial: bad actors constantly try to evade detection
- Scale: billions of posts/day

This is a high-stakes system with regulatory, legal, and ethical implications.',
'["Multi-modal detection (text, image, video, audio)", "Real-time inference (<1s for text, <10s for video)", "Multi-class: hate speech, violence, nudity, spam, etc.", "Multi-language support (100+ languages)", "High precision (>95%) to avoid removing legitimate content", "High recall (>98%) for severe violations", "Human-in-the-loop for borderline cases", "Explainability for appeals", "Adversarial robustness", "Regional policy differences"]',
'{"model_architecture": "Multi-modal models (CLIP, ViT, transformers)", "data_pipeline": "How to get labeled data (human labeling, active learning)", "precision_recall": "Strategy to balance false positives vs false negatives", "adversarial": "Handling adversarial attacks (typos, obfuscation)", "human_loop": "Queue design, reviewer workflow", "explainability": "SHAP, attention, or rule-based explanations", "scaling": "Distributed inference for billions of items", "metrics": "Precision, recall, proactive rate, human review queue size"}',
'["Text Classification (hate speech, spam)", "Image Classification (nudity, violence)", "Video Understanding (frame + audio analysis)", "Multi-modal Fusion", "Human Review Queue", "Active Learning Pipeline", "Adversarial Detection", "Explanation Generator", "Appeal System", "Policy Engine (region-specific rules)"]');


-- Question 45: Design Spam Detection System for Messaging
-- Design Spam Detection System for Messaging (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(45, 2, 'Design Spam Detection System for Messaging', 'medium',
'Design a real-time spam detection system for Meta Messenger/WhatsApp that identifies and blocks spam, scams, and phishing at scale while preserving user privacy.',
'["spam-detection", "classification", "privacy", "meta", "messaging", "adversarial"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(45,
'Meta''s messaging platforms (Messenger, WhatsApp, Instagram DMs) need spam detection:
- Billions of messages daily
- Real-time detection (<100ms)
- Privacy: End-to-end encrypted (WhatsApp)
- Multi-type: spam, scams, phishing, malware links
- Low false positive rate (legitimate messages blocked)
- Handle adversarial attackers (constantly evolving tactics)
- Multi-language support
- On-device ML (for encrypted messages)

Challenge: Balance spam detection with privacy (can''t read WhatsApp messages).',
'["Real-time detection (<100ms per message)", "Privacy-preserving (work with encrypted messages)", "Multi-type: spam, scams, phishing, malware", "Low false positive rate (<0.1%)", "High recall for dangerous scams (>95%)", "On-device models (for WhatsApp)", "Handle text, images, links, files", "Adversarial robustness", "Multi-language support", "Scale to billions of messages/day"]',
'{"privacy": "How to detect spam without reading content", "on_device": "Lightweight models for mobile devices", "features": "Metadata vs content features", "adversarial": "Handling typos, obfuscation, zero-day attacks", "false_positives": "Strategy to minimize blocking legitimate messages", "link_scanning": "Detecting malicious URLs", "user_reports": "Incorporating user feedback", "metrics": "Precision, recall, proactive detection rate"}',
'["Message Classifier (spam vs ham)", "URL Scanner (malware/phishing detection)", "Image OCR + Classification", "Behavioral Signals (message patterns)", "On-device Model (for WhatsApp)", "Server-side Model (for Messenger)", "User Report System", "Challenge Flows (CAPTCHA for suspected spam)", "Adversarial Detection", "Feedback Loop"]');


-- Question 46: Design A/B Testing Platform for ML Experiments
-- Design A/B Testing Platform for ML Experiments (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(46, 2, 'Design A/B Testing Platform for ML Experiments', 'medium',
'Design Meta/Atlassian''s ML experimentation platform that enables safe, fast, statistically rigorous A/B testing of ML models in production.',
'["ab-testing", "experimentation", "infrastructure", "statistics", "meta", "atlassian"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(46,
'Large tech companies run thousands of A/B tests. The platform must:
- Enable data scientists to run ML experiments easily
- Random assignment (users to treatment/control)
- Metric computation (online + offline metrics)
- Statistical testing (p-values, confidence intervals)
- Heterogeneous treatment effects (does it work for all users?)
- Interference handling (network effects, spillover)
- Multi-armed bandits (explore/exploit)
- Staged rollouts (1% → 10% → 100%)
- Automated monitoring (metric guardrails)

Meta runs 1000s of experiments concurrently. Atlassian tests product changes.',
'["Support 1000s of concurrent experiments", "Random assignment with stratification", "Real-time metric computation", "Statistical testing (t-test, bootstrap)", "Heterogeneous treatment effects", "Network effect handling", "Multi-armed bandits", "Automated rollout (gradual)", "Metric guardrails (auto-disable bad experiments)", "Experiment analysis dashboard"]',
'{"randomization": "Proper random assignment, avoiding bias", "metrics": "How to compute online and offline metrics", "statistics": "Statistical rigor, multiple testing correction", "interference": "Handling network effects, spillover", "bandits": "Explore/exploit strategies", "infrastructure": "Scalable, low-latency", "usability": "Easy for data scientists to use", "safety": "Guardrails to prevent bad launches"}',
'["Randomization Service", "Experiment Configuration System", "Metric Computation Pipeline", "Statistical Testing Engine", "Bandit Algorithm", "Staged Rollout Controller", "Metric Guardrails", "Experiment Dashboard", "Heterogeneous Treatment Effect Analysis", "Interference Detection"]');


-- Question 47: Design Search Ranking for Atlassian Products
-- Design Search Ranking for Atlassian Products (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(47, 2, 'Design Search Ranking for Atlassian Products', 'medium',
'Design an ML-powered search system for Atlassian products (Jira, Confluence) that helps users find relevant issues, pages, and projects using natural language queries.',
'["search", "ranking", "nlp", "semantic-search", "atlassian", "enterprise", "jira", "confluence"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(47,
'Atlassian''s products (Jira, Confluence) have extensive search needs:
- Jira: Search issues, projects, filters, boards
- Confluence: Search pages, spaces, attachments, comments
- Cross-product search: Find related items across products
- Natural language: Understand user intent ("bugs from last sprint about login")
- Personalization: Rank based on user''s role, projects, history
- Structured data (Jira fields) + unstructured data (Confluence pages)
- Enterprise scale: 100K+ issues, 50K+ pages per workspace
- Permission-aware (only show what user can access)

Key: Work with limited data (Atlassian is B2B, not consumer scale like Google).',
'["Natural language query understanding", "Multi-source search (Jira, Confluence, comments, attachments)", "Semantic search (beyond keyword matching)", "Personalized ranking", "Permission-aware results", "Sub-second latency", "Handle structured + unstructured data", "Cross-product search", "Auto-complete and suggestions", "Work with limited data (B2B, not web-scale)"]',
'{"query_understanding": "NLP for intent extraction, entity recognition", "semantic_search": "Embeddings for semantic similarity", "ranking": "Learning-to-rank with personalization", "indexing": "Efficient indexing for mixed data types", "permissions": "Secure, fast permission filtering", "personalization": "User context, project access, search history", "limited_data": "How to work with limited training data", "metrics": "Search success rate, CTR, time to find"}',
'["Query Parser (NLP, intent classification)", "Document Indexing (Elasticsearch)", "Semantic Embedding Models (sentence transformers)", "Hybrid Search (keyword + semantic)", "Ranking Model (LambdaMART or neural ranker)", "Permission Filter", "Personalization Layer", "Auto-complete Service", "Cross-product Aggregator", "Click-through Rate Tracker"]');


-- Question 48: Design Real-time Fraud Detection System
-- Design Real-time Fraud Detection System (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(48, 2, 'Design Real-time Fraud Detection System', 'hard',
'Design a real-time fraud detection system for Meta''s payment products (Meta Pay, WhatsApp Pay) that identifies fraudulent transactions with <100ms latency.',
'["fraud-detection", "classification", "real-time", "payments", "meta", "imbalanced-data"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(48,
'Meta''s payment products need fraud detection:
- Real-time: Score transactions in <100ms
- Multi-type fraud: stolen cards, account takeover, fake accounts, money laundering
- Class imbalance: fraud rate <1%
- False positives are costly: block legitimate transactions
- False negatives are costly: allow fraud, chargebacks
- Adversarial: fraudsters constantly adapt
- Explainability: Why was this transaction blocked?
- Regulatory compliance: PCI-DSS, AML, KYC

The system processes millions of transactions daily, losing millions to fraud if ineffective.',
'["Real-time scoring (<100ms per transaction)", "Multi-type fraud detection", "High recall for fraud (>90%)", "Low false positive rate (<2%)", "Handle severe class imbalance (<1% fraud)", "Adversarial robustness", "Explainability for compliance", "Online learning (adapt to new fraud patterns)", "Scale to millions of transactions/day", "Multi-stage: real-time \u2192 post-transaction analysis"]',
'{"model": "Gradient boosting, neural networks, or ensemble", "features": "Transaction, user, device, behavioral features", "imbalance": "Handling class imbalance (SMOTE, class weights)", "adversarial": "Detecting novel fraud patterns", "latency": "Sub-100ms inference", "explainability": "SHAP, rule-based explanations", "online_learning": "Continuous model updates", "metrics": "Precision, recall, F1, fraud loss, false positive rate"}',
'["Real-time Transaction Scorer", "Feature Engineering Pipeline", "Fraud Detection Model (GBDT or NN)", "Rule Engine (known fraud patterns)", "Anomaly Detector (novel fraud)", "Device Fingerprinting", "Behavioral Analytics (velocity checks)", "Post-transaction Analysis", "Explainability Module", "Feedback Loop (confirmed fraud cases)"]');


-- Question 49: Design Video Understanding System for Meta
-- Design Video Understanding System for Meta (HARD)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(49, 2, 'Design Video Understanding System for Meta', 'hard',
'Design Meta''s video understanding system that analyzes billions of videos to enable search, recommendations, content moderation, and monetization.',
'["video-understanding", "multi-modal", "computer-vision", "meta", "reels", "deep-learning"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(49,
'Meta processes billions of videos (Facebook, Instagram, Reels, Stories). The system must:
- Understand video content: objects, actions, scenes, audio, text
- Enable video search ("find videos of surfing in Hawaii")
- Power recommendations (similar videos)
- Content moderation (detect violations)
- Ad placement (find ad-safe content)
- Thumbnail selection (pick engaging frame)
- Auto-captions (accessibility)
- Copyright detection (match against known content)

Challenge: Video processing is expensive (compute, storage). Need efficient models.',
'["Multi-modal understanding (visual, audio, text)", "Scale to billions of videos", "Real-time for short videos (<10s)", "Batch processing for long videos", "Frame-level analysis (scene detection)", "Audio understanding (speech, music, sounds)", "Text extraction (OCR on video)", "Efficient inference (cost-effective)", "Enable search, recommendations, moderation", "Copyright detection"]',
'{"model_architecture": "Video transformers, 3D CNNs, or frame sampling", "multi_modal": "How to fuse visual, audio, text signals", "efficiency": "Cost-effective processing at scale", "embeddings": "Quality of video embeddings for search/recommendations", "scene_detection": "Identifying scene boundaries", "audio_processing": "Speech recognition, music detection", "ocr": "Text extraction from video frames", "metrics": "Video search quality, recommendation CTR, moderation accuracy"}',
'["Video Encoder (frame embeddings)", "Audio Encoder (audio embeddings)", "Text Encoder (captions, OCR)", "Multi-modal Fusion", "Scene Detection", "Object/Action Recognition", "Speech-to-Text", "Thumbnail Selector", "Copyright Matcher", "Video Search Index"]');


-- Question 50: Design Real-time Personalization Engine
-- Design Real-time Personalization Engine (MEDIUM)
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
(50, 2, 'Design Real-time Personalization Engine', 'medium',
'Design a real-time personalization system that adapts Meta/Atlassian products to individual users based on their behavior, preferences, and context.',
'["personalization", "user-modeling", "real-time", "meta", "atlassian", "recommendations"]');

INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
(50,
'Modern products need personalization at scale:
- Meta: Personalize Feed, Reels, notifications, ads
- Atlassian: Personalize Jira dashboards, Confluence recommendations
- Real-time: Update preferences as user interacts
- Cold start: New users have no history
- Context: Time of day, device, location matter
- Privacy: Limited data collection
- Scale: Billions of users
- Latency: <50ms per request

Goal: Show the right content to the right user at the right time.',
'["Real-time preference updates (<50ms)", "Handle billions of users", "Cold start for new users", "Context-aware (time, device, location)", "Privacy-preserving", "Multi-product personalization", "Efficient user representation (embeddings)", "Online learning (user preferences change)", "A/B testing integration", "Explainability (why this recommendation?)"]',
'{"user_modeling": "How to represent users (embeddings, features)", "real_time": "Low-latency updates and inference", "cold_start": "Strategy for new users", "context": "Incorporating temporal, device, location signals", "online_learning": "Continuous preference updates", "privacy": "Working with limited data", "scalability": "Handling billions of users efficiently", "metrics": "Engagement lift, user satisfaction, CTR"}',
'["User Profile Store (preferences, embeddings)", "Real-time Event Stream (user actions)", "User Embedding Model", "Context Feature Service", "Personalization API", "Cold Start Solver", "Online Learning Pipeline", "A/B Testing Integration", "Privacy Controls", "Explainability Module"]');

