#!/usr/bin/env python3
"""
Generate SQL seed file from questions_data.py

Single-purpose script: Converts Python question data to SQL INSERT statements.

Usage:
    python3 scripts/generate_seed_sql.py

Output:
    database/seed_complete.sql (ready to import)
"""

import json
import sys
from pathlib import Path

# Import from single source of truth
sys.path.insert(0, str(Path(__file__).parent))
from questions_data import LEETCODE_QUESTIONS, ML_QUESTIONS


def escape_sql_string(s):
    """Escape single quotes for SQL"""
    if s is None:
        return ""
    return str(s).replace("'", "''")


def generate_leetcode_insert(q, question_id):
    """Generate SQL INSERT statements for a LeetCode question"""
    sql = []
    
    # Add LeetCode URL to hints if it exists
    hints = []
    if 'leetcode_url' in q:
        hints.append(f"LeetCode URL: {q['leetcode_url']}")
    hints_json = json.dumps(hints) if hints else 'null'
    
    # Insert main question
    sql.append(f"""-- {q['title']} ({q['difficulty'].upper()})
INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
({question_id}, 1, '{escape_sql_string(q['title'])}', '{q['difficulty']}',
'{escape_sql_string(q['description'])}',
'{escape_sql_string(json.dumps(q['constraints']))}',
'{escape_sql_string(json.dumps(q['examples']))}',
'{escape_sql_string(json.dumps(q['tags']))}',
'{escape_sql_string(hints_json)}');
""")
    
    # Insert LeetCode-specific data
    sql.append(f"""INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, expected_time_complexity, expected_space_complexity) VALUES
({question_id},
'{escape_sql_string(q['python_sig'])}',
'{escape_sql_string(q['java_sig'])}',
'{escape_sql_string(q['cpp_sig'])}',
'{escape_sql_string(json.dumps(q['test_cases']))}',
'{escape_sql_string(q['time_complexity'])}',
'{escape_sql_string(q['space_complexity'])}');
""")
    
    return "\n".join(sql)


def generate_ml_insert(q, question_id):
    """Generate SQL INSERT statements for an ML System Design question"""
    sql = []
    
    # Insert main question
    sql.append(f"""-- {q['title']} ({q['difficulty'].upper()})
INSERT INTO questions (id, category_id, title, difficulty, description, tags) VALUES
({question_id}, 2, '{escape_sql_string(q['title'])}', '{q['difficulty']}',
'{escape_sql_string(q['description'])}',
'{escape_sql_string(json.dumps(q['tags']))}');
""")
    
    # Insert ML-specific data
    sql.append(f"""INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components) VALUES
({question_id},
'{escape_sql_string(q['scenario'])}',
'{escape_sql_string(json.dumps(q['requirements']))}',
'{escape_sql_string(json.dumps(q['evaluation_criteria']))}',
'{escape_sql_string(json.dumps(q['key_components']))}');
""")
    
    return "\n".join(sql)


def main():
    output_file = Path(__file__).parent.parent / "database" / "seed_complete.sql"
    
    # LEETCODE_QUESTIONS is already optimized to exactly 40 questions (5 Easy, 27 Medium, 8 Hard)
    selected_leetcode = LEETCODE_QUESTIONS
    
    easy_count = len([q for q in selected_leetcode if q['difficulty'] == 'easy'])
    medium_count = len([q for q in selected_leetcode if q['difficulty'] == 'medium'])
    hard_count = len([q for q in selected_leetcode if q['difficulty'] == 'hard'])
    
    print(f"🔧 Generating seed SQL file (Optimized for Meta & Atlassian)...")
    print(f"   LeetCode questions: {len(selected_leetcode)} ({easy_count} Easy, {medium_count} Medium, {hard_count} Hard)")
    print(f"   ML Design questions: {len(ML_QUESTIONS)}")
    
    sql_lines = [
        "-- Complete Seed Data: 40 LeetCode + 10 ML System Design Questions",
        "-- Optimized for Meta & Atlassian Senior ML Engineer Interviews",
        "-- Generated by generate_seed_sql.py",
        "-- ",
        "-- Distribution:",
        f"--   LeetCode: {easy_count} Easy, {medium_count} Medium, {hard_count} Hard = {len(selected_leetcode)} Total",
        f"--   ML Design: {len(ML_QUESTIONS)} questions",
        "--",
        "-- Meta-specific additions: Sparse Vectors, K Closest Points, Buildings with Ocean View, etc.",
        "-- Atlassian-specific: Search/Discovery system for Jira/Confluence",
        "",
        "-- Ensure categories exist",
        "INSERT OR IGNORE INTO question_categories (id, name, description) VALUES",
        "    (1, 'leetcode', 'LeetCode-style coding problems'),",
        "    (2, 'ml_system_design', 'Machine Learning System Design questions');",
        "",
        "-- ============================================",
        "-- LEETCODE QUESTIONS",
        "-- ============================================",
        ""
    ]
    
    question_id = 1
    
    # Add LeetCode questions
    for i, q in enumerate(selected_leetcode, 1):
        sql_lines.append(f"-- Question {question_id}: {q['title']}")
        sql_lines.append(generate_leetcode_insert(q, question_id))
        sql_lines.append("")
        question_id += 1
    
    # Add ML questions
    sql_lines.append("")
    sql_lines.append("-- ============================================")
    sql_lines.append("-- ML SYSTEM DESIGN QUESTIONS")
    sql_lines.append("-- ============================================")
    sql_lines.append("")
    
    for i, q in enumerate(ML_QUESTIONS, 1):
        sql_lines.append(f"-- Question {question_id}: {q['title']}")
        sql_lines.append(generate_ml_insert(q, question_id))
        sql_lines.append("")
        question_id += 1
    
    # Write to file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_lines))
    
    print(f"✅ Generated: {output_file}")
    print(f"   Total questions: {question_id - 1}")
    print(f"   File size: {output_file.stat().st_size / 1024:.1f} KB")
    print("")
    print("📝 To import into database:")
    print("   sqlite3 path/to/interview-prep.db < database/seed_complete.sql")


if __name__ == '__main__':
    main()
