#!/usr/bin/env python3
"""
Generate seed_complete.sql from questions_data_full.py

This script reads the questions data and generates a complete SQL seed file
with all questions, test cases, and solutions.

Usage:
    python3 scripts/generate_seed_sql.py
"""

import json
import sys
from pathlib import Path

# Import questions data
sys.path.insert(0, str(Path(__file__).parent))
from questions_data_full import LEETCODE_QUESTIONS, ML_QUESTIONS


def escape_sql_string(s):
    """Escape single quotes for SQL strings"""
    if s is None:
        return ''
    return str(s).replace("'", "''")


def generate_leetcode_question_sql(q, question_id):
    """Generate SQL INSERT statements for a LeetCode question"""
    sql = []

    # Insert into questions table
    sql.append(f"-- Question {question_id}: {q['title']}")
    sql.append(f"-- {q['title']} ({q['difficulty'].upper()})")

    # Prepare JSON fields
    tags_json = json.dumps(q.get('tags', []))
    hints_json = json.dumps(q.get('hints', []))
    examples_json = json.dumps(q.get('examples', []))
    constraints_json = json.dumps(q.get('constraints', []))

    sql.append(f"""INSERT INTO questions (id, category_id, title, difficulty, description, constraints, examples, tags, hints) VALUES
({question_id}, 1, '{escape_sql_string(q['title'])}', '{q['difficulty']}',
'{escape_sql_string(q['description'])}',
'{escape_sql_string(constraints_json)}',
'{escape_sql_string(examples_json)}',
'{escape_sql_string(tags_json)}',
'{escape_sql_string(hints_json)}');
""")

    # Prepare test cases
    test_cases_json = json.dumps(q.get('test_cases', []))

    # Insert into leetcode_questions table
    sql.append(f"""INSERT INTO leetcode_questions (question_id, function_signature_python, function_signature_java, function_signature_cpp, test_cases, hidden_test_cases, expected_time_complexity, expected_space_complexity, solution_python, solution_java, solution_cpp, solution_explanation) VALUES
({question_id},
'{escape_sql_string(q.get('python_sig', ''))}',
'{escape_sql_string(q.get('java_sig', ''))}',
'{escape_sql_string(q.get('cpp_sig', ''))}',
'{escape_sql_string(test_cases_json)}',
'[]',
'{escape_sql_string(q.get('time_complexity', ''))}',
'{escape_sql_string(q.get('space_complexity', ''))}',
'{escape_sql_string(q.get('solution_python', ''))}',
'{escape_sql_string(q.get('solution_java', ''))}',
'{escape_sql_string(q.get('solution_cpp', ''))}',
'{escape_sql_string(q.get('solution_explanation', ''))}');
""")

    return '\n'.join(sql)


def generate_ml_question_sql(q, question_id):
    """Generate SQL INSERT statements for an ML Design question"""
    sql = []

    # Insert into questions table
    sql.append(f"-- Question {question_id}: {q['title']}")
    sql.append(f"-- {q['title']} ({q['difficulty'].upper()})")

    # Prepare JSON fields
    tags_json = json.dumps(q.get('tags', []))
    hints_json = json.dumps(q.get('hints', []))

    sql.append(f"""INSERT INTO questions (id, category_id, title, difficulty, description, tags, hints) VALUES
({question_id}, 2, '{escape_sql_string(q['title'])}', '{q['difficulty']}',
'{escape_sql_string(q['description'])}',
'{escape_sql_string(tags_json)}',
'{escape_sql_string(hints_json)}');
""")

    # Prepare ML-specific JSON fields
    requirements_json = json.dumps(q.get('requirements', []))
    evaluation_criteria_json = json.dumps(q.get('evaluation_criteria', {}))
    key_components_json = json.dumps(q.get('key_components', []))

    # Insert into ml_design_questions table
    sql.append(f"""INSERT INTO ml_design_questions (question_id, scenario, requirements, evaluation_criteria, key_components, sample_solution) VALUES
({question_id},
'{escape_sql_string(q.get('scenario', ''))}',
'{escape_sql_string(requirements_json)}',
'{escape_sql_string(evaluation_criteria_json)}',
'{escape_sql_string(key_components_json)}',
'{escape_sql_string(q.get('sample_solution', ''))}');
""")

    return '\n'.join(sql)


def generate_seed_sql():
    """Generate the complete seed SQL file"""
    output_path = Path(__file__).parent.parent / 'database' / 'seed_complete.sql'

    with open(output_path, 'w') as f:
        # Header
        f.write("-- Complete seed data for Interview Prep Platform\n")
        f.write("-- Generated from questions_data_full.py\n")
        f.write("-- DO NOT EDIT THIS FILE MANUALLY - regenerate using scripts/generate_seed_sql.py\n\n")

        f.write("-- Clear existing data\n")
        f.write("DELETE FROM feedback;\n")
        f.write("DELETE FROM code_submissions;\n")
        f.write("DELETE FROM design_submissions;\n")
        f.write("DELETE FROM mock_interview_questions;\n")
        f.write("DELETE FROM mock_interviews;\n")
        f.write("DELETE FROM user_progress;\n")
        f.write("DELETE FROM leetcode_questions;\n")
        f.write("DELETE FROM ml_design_questions;\n")
        f.write("DELETE FROM questions;\n\n")

        f.write("-- ============================================\n")
        f.write("-- LEETCODE QUESTIONS (51 questions)\n")
        f.write("-- ============================================\n\n")

        # Generate LeetCode questions
        question_id = 1
        for q in LEETCODE_QUESTIONS:
            f.write(generate_leetcode_question_sql(q, question_id))
            f.write("\n\n")
            question_id += 1

        f.write("-- ============================================\n")
        f.write("-- ML SYSTEM DESIGN QUESTIONS (10 questions)\n")
        f.write("-- ============================================\n\n")

        # Generate ML Design questions
        for q in ML_QUESTIONS:
            f.write(generate_ml_question_sql(q, question_id))
            f.write("\n\n")
            question_id += 1

    print(f"✅ Generated {output_path}")
    print(f"   - {len(LEETCODE_QUESTIONS)} LeetCode questions")
    print(f"   - {len(ML_QUESTIONS)} ML System Design questions")
    print(f"   - Total: {len(LEETCODE_QUESTIONS) + len(ML_QUESTIONS)} questions")


if __name__ == '__main__':
    generate_seed_sql()
